### ISSUE TITLE
Crash with Foamfix

### ISSUE THREAD

**Issue by judgekreep** [LoliKingdom/LoliASM#111]
I encounter this crash when only using Loliasm and Foamfix.
Reproduce it by having these two mods (and mixin); load into a world - - for me, it happened in a non-flat world.

**Loliasm version: 5.3
Foamfix version: 0.10.14**

```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Uh... Did I do that?

Time: 2022-05-31 13:50:54 CDT
Description: Unexpected error

java.lang.NullPointerException
    at pl.asie.foamfix.client.FastTextureAtlasSprite.updateAnimation(FastTextureAtlasSprite.java:82)
    at net.minecraft.client.renderer.texture.TextureMap.updateAnimations(TextureMap.java:584)
    at net.minecraft.client.renderer.texture.TextureMap.tick(TextureMap.java:385)
    at net.minecraft.client.renderer.texture.TextureManager.tick(TextureManager.java:130)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1731)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3611)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['JudgeKreep'/1357, l='MpServer', x=-190.50, y=69.00, z=17.50]]
  Chunk stats: MultiplayerChunkCache: 361, 361
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-192,64,20), Chunk: (at 0,4,4 in -12,1; contains blocks -192,0,16 to -177,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 192 game time, 192 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 65 total; [EntityZombie['Zombie'/1415, l='MpServer', x=-257.50, y=40.00, z=21.50], EntityZombie['Zombie'/1417, l='MpServer', x=-255.50, y=40.00, z=17.50], EntityBat['Bat'/1546, l='MpServer', x=-153.22, y=19.07, z=-23.41], EntitySkeleton['Skeleton'/396, l='MpServer', x=-247.50, y=40.00, z=3.50], EntitySkeleton['Skeleton'/397, l='MpServer', x=-247.50, y=40.00, z=5.50], EntityCreeper['Creeper'/398, l='MpServer', x=-255.50, y=43.00, z=28.50], EntityZombie['Zombie'/399, l='MpServer', x=-240.59, y=29.00, z=44.50], EntityZombie['Zombie'/400, l='MpServer', x=-240.50, y=29.00, z=45.50], EntityBat['Bat'/401, l='MpServer', x=-249.72, y=44.69, z=38.63], EntitySkeleton['Skeleton'/402, l='MpServer', x=-252.22, y=57.00, z=34.49], EntityBat['Bat'/403, l='MpServer', x=-249.31, y=44.26, z=37.54], EntityCreeper['Creeper'/1684, l='MpServer', x=-220.50, y=16.00, z=85.50], EntityCreeper['Creeper'/1685, l='MpServer', x=-221.50, y=16.00, z=83.50], EntityCreeper['Creeper'/1686, l='MpServer', x=-223.50, y=16.00, z=81.50], EntityCreeper['Creeper'/1687, l='MpServer', x=-222.50, y=16.00, z=81.50], EntityCow['Cow'/537, l='MpServer', x=-190.50, y=69.00, z=13.50], EntitySpider['Spider'/1819, l='MpServer', x=-210.50, y=45.00, z=-62.50], EntityZombie['Zombie'/1693, l='MpServer', x=-228.50, y=29.00, z=56.50], EntitySkeleton['Skeleton'/1823, l='MpServer', x=-207.50, y=45.00, z=-61.50], EntitySkeleton['Skeleton'/1824, l='MpServer', x=-208.50, y=45.00, z=-61.50], EntityPlayerSP['JudgeKreep'/1357, l='MpServer', x=-190.50, y=69.00, z=17.50], EntityZombie['Zombie'/1574, l='MpServer', x=-143.47, y=64.00, z=97.76], EntityWolf['Wolf'/679, l='MpServer', x=-121.50, y=69.00, z=74.50], EntityWolf['Wolf'/680, l='MpServer', x=-120.50, y=69.00, z=77.50], EntityWolf['Wolf'/681, l='MpServer', x=-122.50, y=68.00, z=76.12], EntityCow['Cow'/426, l='MpServer', x=-236.50, y=69.00, z=44.50], EntityWolf['Wolf'/682, l='MpServer', x=-126.50, y=68.00, z=80.50], EntitySpider['Spider'/1578, l='MpServer', x=-144.12, y=64.00, z=96.73], EntityCow['Cow'/427, l='MpServer', x=-235.50, y=69.00, z=42.50], EntityCow['Cow'/428, l='MpServer', x=-231.16, y=68.00, z=50.57], EntityZombie['Zombie'/1590, l='MpServer', x=-238.50, y=63.00, z=55.50], EntityCow['Cow'/439, l='MpServer', x=-209.50, y=65.00, z=-6.50], EntityCow['Cow'/440, l='MpServer', x=-208.50, y=67.00, z=-1.50], EntityItem['item.tile.gravel'/441, l='MpServer', x=-211.65, y=24.00, z=69.76], EntityCreeper['Creeper'/1849, l='MpServer', x=-127.50, y=63.00, z=-38.50], EntityItem['item.tile.gravel'/442, l='MpServer', x=-213.76, y=23.00, z=66.36], EntityCreeper['Creeper'/1850, l='MpServer', x=-127.50, y=63.00, z=-43.50], EntityCreeper['Creeper'/1871, l='MpServer', x=-266.50, y=38.00, z=64.50], EntityCreeper['Creeper'/1872, l='MpServer', x=-264.50, y=38.00, z=66.50], EntityBat['Bat'/339, l='MpServer', x=-263.98, y=23.62, z=32.10], EntityCreeper['Creeper'/340, l='MpServer', x=-258.51, y=44.00, z=26.78], EntityCreeper['Creeper'/1492, l='MpServer', x=-220.13, y=44.01, z=26.47], EntityCreeper['Creeper'/341, l='MpServer', x=-258.50, y=39.00, z=23.50], EntityBat['Bat'/342, l='MpServer', x=-266.25, y=38.30, z=60.52], EntitySkeleton['Skeleton'/343, l='MpServer', x=-256.50, y=46.00, z=65.50], EntityBat['Bat'/344, l='MpServer', x=-259.10, y=32.85, z=63.80], EntitySkeleton['Skeleton'/1764, l='MpServer', x=-250.50, y=46.00, z=10.50], EntityZombie['Zombie'/1766, l='MpServer', x=-191.50, y=37.00, z=83.50], EntitySkeleton['Skeleton'/1895, l='MpServer', x=-176.50, y=43.00, z=70.50], EntityCow['Cow'/488, l='MpServer', x=-206.50, y=67.00, z=-3.50], EntityCow['Cow'/489, l='MpServer', x=-207.50, y=67.00, z=-0.50], EntityZombie['Zombie'/2025, l='MpServer', x=-247.50, y=42.00, z=62.50], EntityCow['Cow'/490, l='MpServer', x=-197.02, y=69.00, z=13.52], EntitySkeleton['Skeleton'/2026, l='MpServer', x=-246.50, y=42.00, z=62.50], EntityCow['Cow'/491, l='MpServer', x=-194.50, y=68.00, z=11.50], EntityCow['Cow'/619, l='MpServer', x=-151.50, y=64.00, z=-38.50], EntitySkeleton['Skeleton'/2027, l='MpServer', x=-246.50, y=42.00, z=64.50], EntityCow['Cow'/492, l='MpServer', x=-192.50, y=69.00, z=12.50], EntityCow['Cow'/620, l='MpServer', x=-149.32, y=65.00, z=-35.51], EntityCow['Cow'/621, l='MpServer', x=-148.42, y=65.00, z=-35.20], EntityCow['Cow'/622, l='MpServer', x=-151.50, y=64.00, z=-38.50], EntityZombie['Zombie'/1778, l='MpServer', x=-211.50, y=24.00, z=72.50], EntityBat['Bat'/2043, l='MpServer', x=-220.15, y=36.39, z=46.50], EntityBat['Bat'/1404, l='MpServer', x=-230.75, y=15.00, z=44.50], EntityBat['Bat'/2044, l='MpServer', x=-225.75, y=36.46, z=45.63]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_332, IBM Corporation
  Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220422_375 (JIT enabled, AOT enabled)
                   OpenJ9   - 9a84ec34e
                   OMR      - ab24b6666
                   JCL      - 0b8b8af39a based on jdk8u332-b09), Eclipse OpenJ9
  Memory: 5911146560 bytes (5637 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
  JVM Flags: 24 total; -Xoptionsfile=C:\Program Files\Semeru\jre-8.0.332.9-openj9\bin\default\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms7G -Xmx7G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 LoliASM 5.3 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID          | Version        | Source                        | Signature                                |
       |:------ |:----------- |:-------------- |:----------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft   | 1.12.2         | minecraft.jar                 | None                                     |
       | LCHIJA | mcp         | 9.42           | minecraft.jar                 | None                                     |
       | LCHIJA | FML         | 8.0.99.99      | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge       | 14.23.5.2860   | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | mixinbooter | 4.2            | minecraft.jar                 | None                                     |
       | LCHIJA | foamfixcore | 7.7.4          | minecraft.jar                 | None                                     |
       | LCHIJA | foamfix     | 0.10.14-1.12.2 | foamfix-0.10.14-1.12.2.jar    | None                                     |
       | LCHIJA | loliasm     | 5.3            | loliasm-5.3.jar               | None                                     |
  Loaded coremods (and transformers): MixinBooter (!mixinbooter-4.2.jar)
                                        
                                      LoliASM (loliasm-5.3.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.09' Renderer: 'NVIDIA GeForce GT 1030/PCIe/SSE2'
  Suspected Mods: FoamFix (foamfix)
  Launched Version: 1.12.2-forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 497.09, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 1.12.2 Main (Firewolfv1.74).zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD FX(tm)-4300 Quad-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

```

**Comment by Rongmario** [comment]
Can you send me your loliasm and foamfix configuration files?

**Comment by platinumphoenix2** [comment]
I deleted my original config files just to confirm that it wasn't that - - I still crashed with the default config files.

Here they are in any case.
Loliasm: https://pastebin.com/w9dDD2Uz
Foamfix: https://pastebin.com/ygdG8ewZ

**Comment by Rongmario** [comment]
Just wanted to know the config combinations, thanks.

**Comment by xJon** [comment]
Still occurs with the latest FoamFix version - https://mclo.gs/ma5dfOu

**Comment by platinumphoenix2** [comment]
Setting `onDemandAnimatedTextures` to `false` seems to prevent the crash for me.

Tested on v5.6
