### ISSUE TITLE
Error in the Logs Regarding LoliASM and BetterPortals

### ISSUE THREAD

**Issue by reddvilzz** [LoliKingdom/LoliASM#120]
I'm having this error though it's not fatal but just wondering what was it about when looking some of the logs, does this affect anything?

> [03:19:22] [pool-13-thread-1/WARN] [betterportals/view]: Failed to determine view of task: 
java.lang.Exception: null
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.wrapTask(ViewDemuxingTaskQueue.kt:46) ~[ViewDemuxingTaskQueue.class:?]
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.offer(ViewDemuxingTaskQueue.kt:86) ~[ViewDemuxingTaskQueue.class:?]
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.offer(ViewDemuxingTaskQueue.kt:16) ~[ViewDemuxingTaskQueue.class:?]
	at java.util.AbstractQueue.add(AbstractQueue.java:95) ~[?:1.8.0_312]
	at net.minecraft.client.Minecraft.addScheduledTask(Minecraft.java:3159) ~[bib.class:?]
	at zone.rong.loliasm.client.sprite.FramesTextureData.size(FramesTextureData.java:58) ~[FramesTextureData.class:?]
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.getFrameCount(TextureAtlasSprite.java:218) ~[cdq.class:?]
	at mezz.jei.color.ColorGetter.getBufferedImage(ColorGetter.java:152) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.getColors(ColorGetter.java:127) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.getBlockColors(ColorGetter.java:123) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.unsafeGetColors(ColorGetter.java:95) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.getColors(ColorGetter.java:78) ~[ColorGetter.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getColors(ItemStackHelper.java:110) ~[ItemStackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getColors(ItemStackHelper.java:29) ~[ItemStackHelper.class:?]
	at mezz.jei.ingredients.IngredientInformation.getColorStrings(IngredientInformation.java:55) ~[IngredientInformation.class:?]
	at mezz.jei.ingredients.IngredientListElement.getColorStrings(IngredientListElement.java:149) ~[IngredientListElement.class:?]
	at mezz.jei.search.PrefixInfo.getStrings(PrefixInfo.java:87) ~[PrefixInfo.class:?]
	at mezz.jei.search.PrefixedSearchable.submit(PrefixedSearchable.java:41) ~[PrefixedSearchable.class:?]
	at mezz.jei.search.AsyncPrefixedSearchable.lambda$submitAll$0(AsyncPrefixedSearchable.java:56) ~[AsyncPrefixedSearchable.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[03:19:22] [pool-13-thread-1/WARN] [betterportals/view]: Suppressing further warnings for tasks originating from zone.rong.loliasm.client.sprite.FramesTextureData.size(FramesTextureData.java:58)
[03:19:48] [pool-13-thread-1/WARN] [betterportals/view]: Failed to determine view of task: 
java.lang.Exception: null
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.wrapTask(ViewDemuxingTaskQueue.kt:46) ~[ViewDemuxingTaskQueue.class:?]
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.offer(ViewDemuxingTaskQueue.kt:86) ~[ViewDemuxingTaskQueue.class:?]
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.offer(ViewDemuxingTaskQueue.kt:16) ~[ViewDemuxingTaskQueue.class:?]
	at java.util.AbstractQueue.add(AbstractQueue.java:95) ~[?:1.8.0_312]
	at net.minecraft.client.Minecraft.addScheduledTask(Minecraft.java:3159) ~[bib.class:?]
	at zone.rong.loliasm.client.sprite.FramesTextureData.get(FramesTextureData.java:49) ~[FramesTextureData.class:?]
	at zone.rong.loliasm.client.sprite.FramesTextureData.get(FramesTextureData.java:17) ~[FramesTextureData.class:?]
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.getFrameTextureData(TextureAtlasSprite.java:213) ~[cdq.class:?]
	at slimeknights.tconstruct.library.client.texture.TextureColoredTexture.preProcess(TextureColoredTexture.java:51) ~[TextureColoredTexture.class:?]
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.processData(AbstractColoredTexture.java:74) ~[AbstractColoredTexture.class:?]
	at slimeknights.tconstruct.library.client.texture.AbstractColoredTexture.load(AbstractColoredTexture.java:63) ~[AbstractColoredTexture.class:?]
	at slimeknights.tconstruct.library.client.texture.TextureColoredTexture.load(TextureColoredTexture.java:44) ~[TextureColoredTexture.class:?]
	at zone.rong.loliasm.client.sprite.FramesTextureData.load(FramesTextureData.java:83) ~[FramesTextureData.class:?]
	at zone.rong.loliasm.client.sprite.FramesTextureData.size(FramesTextureData.java:57) ~[FramesTextureData.class:?]
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.getFrameCount(TextureAtlasSprite.java:218) ~[cdq.class:?]
	at mezz.jei.color.ColorGetter.getBufferedImage(ColorGetter.java:152) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.getColors(ColorGetter.java:127) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.getItemColors(ColorGetter.java:105) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.unsafeGetColors(ColorGetter.java:97) ~[ColorGetter.class:?]
	at mezz.jei.color.ColorGetter.getColors(ColorGetter.java:78) ~[ColorGetter.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getColors(ItemStackHelper.java:110) ~[ItemStackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getColors(ItemStackHelper.java:29) ~[ItemStackHelper.class:?]
	at mezz.jei.ingredients.IngredientInformation.getColorStrings(IngredientInformation.java:55) ~[IngredientInformation.class:?]
	at mezz.jei.ingredients.IngredientListElement.getColorStrings(IngredientListElement.java:149) ~[IngredientListElement.class:?]
	at mezz.jei.search.PrefixInfo.getStrings(PrefixInfo.java:87) ~[PrefixInfo.class:?]
	at mezz.jei.search.PrefixedSearchable.submit(PrefixedSearchable.java:41) ~[PrefixedSearchable.class:?]
	at mezz.jei.search.AsyncPrefixedSearchable.lambda$submitAll$0(AsyncPrefixedSearchable.java:56) ~[AsyncPrefixedSearchable.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[03:19:48] [pool-13-thread-1/WARN] [betterportals/view]: Suppressing further warnings for tasks originating from zone.rong.loliasm.client.sprite.FramesTextureData.get(FramesTextureData.java:49)

**Comment by Lonelyxiya** [comment]
You should send the log file inside the logs.

**Comment by reddvilzz** [comment]
Here is the latest log

[latest.log](https://github.com/LoliKingdom/LoliASM/files/9132656/latest.log)

**Comment by Rongmario** [comment]
Seems like the log doesn't have the crash in?

**Comment by reddvilzz** [comment]
Yes, it's not a crash log. I'm just wondering if the error will cause anything game breaking or not?

**Comment by embeddedt** [comment]
I don't think this will cause issues. This looks like BetterPortals trying to detect which client world it should provide when the task to clear sprite data is running. I don't believe LoliASM cares exactly which world, so it shouldn't cause any problems in game aside from the log messages.

**Comment by reddvilzz** [comment]
Okay thanks, I'll close this.
