### ISSUE TITLE
Crash "java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker"

### ISSUE THREAD

**Issue by rinart73** [LoliKingdom/LoliASM#124]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Modlist:
```
loliasm-5.6
```

Crash log:
```
[17:23:36] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:36] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:36] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[17:23:36] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_333, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_333
[17:23:37] [main/INFO] [FML]: Searching C:\Users\user\AppData\Roaming\.minecraft\mods for mods
[17:23:37] [main/INFO] [FML]: Searching C:\Users\user\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[17:23:37] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[17:23:37] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:23:37] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[17:23:37] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in future-mc-0.2.10.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[17:23:37] [main/WARN] [FML]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[17:23:37] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from loliasm-5.6.jar
[17:23:37] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine-1.12.2_HD_U_G5.jar
[17:23:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:23:37] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[17:23:37] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_333]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Exception in thread "main" [17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:23:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by rinart73** [comment]
UPD: Apologies, didn't notice that MixinBooter is needed. Although usually Forge displays required dependencies instead of just crashing

**Comment by Rongmario** [comment]
Not much I can do atm, it's crashing before Forge has knowledge of what mods are installed.
