### ISSUE TITLE
Incompability w. SGCraft (again)

### ISSUE THREAD

**Issue by Shazuli** [LoliKingdom/LoliASM#137]
***Hi***

A crash with [SGCraft](https://github.com/AlmuraDev/SGCraft) (v2.0.5) and LoliASM (5.6) has started to occur again. This time when you start breaking a Stargate block in survival.

![2022-09-01_12 19 38](https://user-images.githubusercontent.com/9884180/187891891-2777e0c6-43b3-44ce-88c9-87db013764cf.png)

<details>
  <summary>crash-2022-09-01_12.07.55-client.txt</summary>

```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Quite honestly, I wouldn't worry myself about that.

Time: 2022-09-01 12:07:55 CEST
Description: Tesselating block model

java.lang.NullPointerException
    at net.minecraftforge.client.model.pipeline.VertexLighterFlat.setTexture(VertexLighterFlat.java:526)
    at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:93)
    at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:73)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:102)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelFlat(ForgeBlockModelRenderer.java:61)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:47)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:38)
    at gcewing.sg.BaseAORenderingManager$CustomBlockRendererDispatcher.renderBlockDamage(BaseAORenderingManager.java:73)
    at net.minecraft.client.renderer.RenderGlobal.drawBlockDamageTexture(RenderGlobal.java:1938)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1375)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block model being tesselated --
  Block: sgcraft:stargatebase[facing=north]
  Block location: World: (-139,70,248), Chunk: (at 5,4,8 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Using AO: false

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['simon_kungen'/380, l='MpServer', x=-138.35, y=70.00, z=250.20]]
  Chunk stats: MultiplayerChunkCache: 552, 552
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-144,64,256), Chunk: (at 0,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 711 game time, 711 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 116 total; [EntityHorse['Horse'/256, l='MpServer', x=-71.01, y=69.00, z=316.94], EntityHorse['Horse'/257, l='MpServer', x=-78.14, y=70.00, z=304.49], EntityCreeper['Creeper'/265, l='MpServer', x=-71.50, y=40.00, z=322.50], EntityCreeper['Creeper'/281, l='MpServer', x=-62.50, y=52.00, z=253.50], EntitySkeleton['Skeleton'/282, l='MpServer', x=-59.50, y=53.00, z=255.50], EntityCreeper['Creeper'/283, l='MpServer', x=-63.65, y=51.00, z=255.49], EntitySkeleton['Skeleton'/284, l='MpServer', x=-62.50, y=35.00, z=257.50], EntityCow['Cow'/285, l='MpServer', x=-61.50, y=75.00, z=271.50], EntitySkeleton['Skeleton'/286, l='MpServer', x=-61.50, y=31.00, z=274.50], EntityCow['Cow'/291, l='MpServer', x=-63.50, y=75.00, z=273.50], EntityCow['Cow'/292, l='MpServer', x=-63.50, y=75.00, z=274.50], EntityHorse['Horse'/301, l='MpServer', x=-63.50, y=71.00, z=307.50], EntityHorse['Horse'/302, l='MpServer', x=-62.50, y=70.00, z=309.50], EntityChicken['Chicken'/56, l='MpServer', x=-218.59, y=70.28, z=175.50], EntityChicken['Chicken'/59, l='MpServer', x=-216.50, y=68.00, z=174.50], EntityCreeper['Creeper'/60, l='MpServer', x=-213.50, y=29.00, z=220.50], EntityCreeper['Creeper'/65, l='MpServer', x=-217.50, y=17.00, z=322.50], EntitySkeleton['Skeleton'/75, l='MpServer', x=-197.50, y=22.00, z=180.50], EntityCreeper['Creeper'/76, l='MpServer', x=-205.50, y=29.00, z=184.50], EntityCreeper['Creeper'/77, l='MpServer', x=-207.50, y=29.00, z=183.50], EntitySkeleton['Skeleton'/78, l='MpServer', x=-197.51, y=32.00, z=185.79], EntitySkeleton['Skeleton'/79, l='MpServer', x=-206.71, y=36.00, z=207.49], EntityBat['Bat'/80, l='MpServer', x=-201.03, y=26.81, z=231.49], EntitySquid['Squid'/82, l='MpServer', x=-198.45, y=61.00, z=233.38], EntityCreeper['Creeper'/83, l='MpServer', x=-193.43, y=36.00, z=244.80], EntityPig['Pig'/84, l='MpServer', x=-198.50, y=69.00, z=280.50], EntityPig['Pig'/85, l='MpServer', x=-197.50, y=69.00, z=280.50], EntityPig['Pig'/86, l='MpServer', x=-198.50, y=69.00, z=282.50], EntityPig['Pig'/87, l='MpServer', x=-198.50, y=68.00, z=284.50], EntityPig['Pig'/90, l='MpServer', x=-181.67, y=71.00, z=172.50], EntityPig['Pig'/91, l='MpServer', x=-183.37, y=71.00, z=173.69], EntitySkeleton['Skeleton'/93, l='MpServer', x=-181.86, y=47.00, z=214.55], EntityCreeper['Creeper'/94, l='MpServer', x=-177.50, y=49.00, z=213.50], EntityBat['Bat'/95, l='MpServer', x=-181.26, y=42.95, z=235.25], EntityZombie['Zombie'/96, l='MpServer', x=-187.49, y=36.13, z=249.93], EntityPig['Pig'/97, l='MpServer', x=-177.50, y=68.00, z=283.50], EntityPig['Pig'/98, l='MpServer', x=-177.50, y=68.00, z=282.50], EntityPig['Pig'/99, l='MpServer', x=-178.50, y=68.00, z=281.50], EntityPig['Pig'/100, l='MpServer', x=-178.50, y=68.00, z=283.50], EntityPig['Pig'/111, l='MpServer', x=-173.67, y=70.00, z=171.48], EntitySkeleton['Skeleton'/112, l='MpServer', x=-174.50, y=26.00, z=296.50], EntityPig['Pig'/123, l='MpServer', x=-145.50, y=66.00, z=178.50], EntityPig['Pig'/124, l='MpServer', x=-145.50, y=66.00, z=179.50], EntityPig['Pig'/125, l='MpServer', x=-149.50, y=70.00, z=180.50], EntityPig['Pig'/126, l='MpServer', x=-145.50, y=70.00, z=182.50], EntityBat['Bat'/127, l='MpServer', x=-150.46, y=12.82, z=198.36], EntityBat['Bat'/128, l='MpServer', x=-151.90, y=12.69, z=198.20], EntityPlayerSP['simon_kungen'/380, l='MpServer', x=-138.35, y=70.00, z=250.20], EntitySlime['Slime'/129, l='MpServer', x=-152.74, y=20.00, z=247.40], EntitySlime['Slime'/130, l='MpServer', x=-149.81, y=21.12, z=241.50], EntitySheep['Sheep'/131, l='MpServer', x=-159.50, y=66.00, z=298.50], EntitySheep['Sheep'/132, l='MpServer', x=-158.49, y=67.00, z=290.79], EntitySheep['Sheep'/133, l='MpServer', x=-157.50, y=66.00, z=302.50], EntitySheep['Sheep'/134, l='MpServer', x=-152.73, y=67.00, z=305.46], EntityZombie['Zombie'/140, l='MpServer', x=-135.50, y=19.00, z=188.50], EntityZombie['Zombie'/141, l='MpServer', x=-136.50, y=19.00, z=188.50], EntityZombie['Zombie'/142, l='MpServer', x=-135.50, y=19.00, z=186.50], EntitySkeleton['Skeleton'/145, l='MpServer', x=-123.34, y=18.00, z=174.70], EntitySkeleton['Skeleton'/146, l='MpServer', x=-123.61, y=18.00, z=173.98], EntityBat['Bat'/150, l='MpServer', x=-114.93, y=18.10, z=175.39], EntitySkeleton['Skeleton'/151, l='MpServer', x=-118.30, y=23.00, z=178.70], EntitySkeleton['Skeleton'/152, l='MpServer', x=-117.52, y=23.00, z=174.79], EntitySkeleton['Skeleton'/153, l='MpServer', x=-119.21, y=23.00, z=178.08], EntityZombie['Zombie'/154, l='MpServer', x=-121.25, y=23.00, z=178.48], EntitySpider['Spider'/155, l='MpServer', x=-119.99, y=33.00, z=199.00], EntityEnderman['Enderman'/156, l='MpServer', x=-125.50, y=15.00, z=227.50], EntityCow['Cow'/157, l='MpServer', x=-113.48, y=70.00, z=227.46], EntityCreeper['Creeper'/181, l='MpServer', x=-108.50, y=26.00, z=198.50], EntityItem['item.tile.flower1.dandelion'/182, l='MpServer', x=-102.68, y=63.00, z=194.56], EntityCow['Cow'/183, l='MpServer', x=-107.50, y=70.00, z=222.50], EntitySkeleton['Skeleton'/184, l='MpServer', x=-110.50, y=15.00, z=225.50], EntityBat['Bat'/185, l='MpServer', x=-106.75, y=40.10, z=233.75], EntityCow['Cow'/186, l='MpServer', x=-107.50, y=70.00, z=225.50], EntityCow['Cow'/187, l='MpServer', x=-111.50, y=70.00, z=228.50], EntityItem['item.tile.torch'/188, l='MpServer', x=-99.33, y=37.00, z=259.44], EntityItem['item.item.seeds'/189, l='MpServer', x=-105.44, y=68.00, z=272.80], EntityBat['Bat'/190, l='MpServer', x=-105.56, y=44.66, z=299.90], EntityBat['Bat'/191, l='MpServer', x=-93.46, y=43.07, z=289.69], EntityMinecartChest['Minecart with Chest'/192, l='MpServer', x=-100.51, y=40.00, z=328.50], EntityItem['item.tile.gravel'/203, l='MpServer', x=-85.90, y=25.00, z=206.44], EntitySkeleton['Skeleton'/204, l='MpServer', x=-87.50, y=38.00, z=226.11], EntitySkeleton['Skeleton'/205, l='MpServer', x=-86.50, y=38.00, z=227.50], EntitySkeleton['Skeleton'/206, l='MpServer', x=-87.50, y=38.00, z=228.50], EntitySkeleton['Skeleton'/207, l='MpServer', x=-86.50, y=38.00, z=230.50], EntityZombie['Zombie'/208, l='MpServer', x=-98.22, y=38.00, z=232.40], EntityZombie['Zombie'/209, l='MpServer', x=-91.50, y=38.00, z=230.50], EntityZombie['Zombie'/210, l='MpServer', x=-90.50, y=38.00, z=231.50], EntityBat['Bat'/211, l='MpServer', x=-81.25, y=40.10, z=225.61], EntitySkeleton['Skeleton'/212, l='MpServer', x=-95.50, y=13.00, z=240.50], EntitySkeleton['Skeleton'/213, l='MpServer', x=-89.50, y=41.00, z=298.50], EntityHorse['Horse'/214, l='MpServer', x=-85.64, y=70.00, z=301.10], EntityHorse['Horse'/215, l='MpServer', x=-87.39, y=70.00, z=301.23], EntityHorse['Horse'/216, l='MpServer', x=-86.33, y=70.00, z=303.01], EntityHorse['Horse'/217, l='MpServer', x=-83.68, y=70.00, z=301.98], EntityItem['item.tile.rail'/218, l='MpServer', x=-87.89, y=45.00, z=308.13], EntityMinecartChest['Minecart with Chest'/219, l='MpServer', x=-85.50, y=45.06, z=310.50], EntityItem['item.tile.torch'/220, l='MpServer', x=-84.83, y=37.00, z=307.96], EntityBat['Bat'/236, l='MpServer', x=-66.48, y=25.27, z=185.54], EntityBat['Bat'/237, l='MpServer', x=-65.22, y=28.37, z=205.10], EntityEnderman['Enderman'/238, l='MpServer', x=-79.50, y=17.00, z=222.50], EntityBat['Bat'/239, l='MpServer', x=-69.88, y=40.10, z=237.38], EntitySkeleton['Skeleton'/240, l='MpServer', x=-71.50, y=34.00, z=225.50], EntityBat['Bat'/241, l='MpServer', x=-65.68, y=38.10, z=252.56], EntityMinecartChest['Minecart with Chest'/242, l='MpServer', x=-68.50, y=41.06, z=264.50], EntityBat['Bat'/243, l='MpServer', x=-69.64, y=38.17, z=259.12], EntityMinecartChest['Minecart with Chest'/244, l='MpServer', x=-71.50, y=42.06, z=286.50], EntityCow['Cow'/245, l='MpServer', x=-66.50, y=75.00, z=274.50], EntityCow['Cow'/246, l='MpServer', x=-70.19, y=74.00, z=282.50], EntityCow['Cow'/247, l='MpServer', x=-70.50, y=74.00, z=283.50], EntityCow['Cow'/248, l='MpServer', x=-70.50, y=74.00, z=284.50], EntityCow['Cow'/249, l='MpServer', x=-70.24, y=74.00, z=286.54], EntityItem['item.tile.torch'/250, l='MpServer', x=-76.46, y=40.00, z=303.13], EntityZombie['Zombie'/251, l='MpServer', x=-66.50, y=28.00, z=311.50], EntityBat['Bat'/252, l='MpServer', x=-62.82, y=33.02, z=323.03], EntityHorse['Horse'/254, l='MpServer', x=-69.90, y=69.00, z=316.74], EntityHorse['Horse'/255, l='MpServer', x=-67.41, y=70.00, z=310.47]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 5.15.60-1-MANJARO
  Java Version: 1.8.0_311, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1569847208 bytes (1497 MB) / 2151153664 bytes (2051 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 2 total; -Xms1024m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID          | Version      | Source                                  | Signature                                |
       |:------ |:----------- |:------------ |:--------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft   | 1.12.2       | minecraft.jar                           | None                                     |
       | LCHIJA | mcp         | 9.42         | minecraft.jar                           | None                                     |
       | LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge       | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | mixinbooter | 5.0          | minecraft.jar                           | None                                     |
       | LCHIJA | loliasm     | 5.6          | loliasm-5.6.jar                         | None                                     |
       | LCHIJA | sgcraft     | 2.0.3        | SGCraft-2.0.5.jar                       | None                                     |
  Loaded coremods (and transformers): MixinBooter (!mixinbooter-5.0.jar)
                                        
                                      LoliASM (loliasm-5.6.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 470.141.03' Renderer: 'NVIDIA GeForce GTX 660/PCIe/SSE2'
  Suspected Mods: Forge Mod Loader (FML), Minecraft Forge (forge), SG Craft (sgcraft)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 660/PCIe/SSE2 GL version 4.6.0 NVIDIA 470.141.03, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
```

**Comment by Ramog** [comment]
@Rongmario I wonder when will that v6 come out? Been quite annoyed by this bug since it makes the stargates very hard to work with. So I had to get rid of LoliASM. Hope this gets fixed soon, since I really miss the improvements.

**Comment by xJon** [comment]
Perhaps there's a config option that can be disabled as a workaround
