### ISSUE TITLE
Incompatibility with Inertia client

### ISSUE THREAD

**Issue by AntonIXO** [LoliKingdom/LoliASM#142]
I tried to start Minecraft with LoliASM and Inertia and got this crash: https://mclo.gs/srLHGOH
No other mods has been installed

`
java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.api.utils.BetterBlockPos
--
9 | at baritone.api.utils.BetterBlockPos.<init>(Unknown Source)
10 | at baritone.api.utils.BetterBlockPos.<clinit>(Unknown Source)
11 | at baritone.api.utils.IPlayerContext.playerFeet(Unknown Source)
12 | at baritone.j.a(Unknown Source)
13 | at baritone.j.onTick(Unknown Source)
14 | at baritone.cf.a(Unknown Source)
15 | at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
16 | at baritone.cf.onTick(Unknown Source)
17 | at net.minecraft.client.Minecraft.handler$zdo000$runTick(Minecraft.java)
18 | at net.minecraft.client.Minecraft.runTick(Minecraft.java:1755)
19 | at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
20 | at net.minecraft.client.Minecraft.run(Minecraft.java:4114)
21 | at net.minecraft.client.main.Main.main(SourceFile:123)
22 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
24 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25 | at java.lang.reflect.Method.invoke(Method.java:498)
26 | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
27 | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
28 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
30 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
31 | at java.lang.reflect.Method.invoke(Method.java:498)
32 | at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
33 | at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
34 | at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
35 | at org.polymc.EntryPoint.listen(EntryPoint.java:144)
36 | at org.polymc.EntryPoint.main(EntryPoint.java:74)

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.api.utils.BetterBlockPos
    at baritone.api.utils.BetterBlockPos.<init>(Unknown Source)
    at baritone.api.utils.BetterBlockPos.<clinit>(Unknown Source)
    at baritone.api.utils.IPlayerContext.playerFeet(Unknown Source)
    at baritone.j.a(Unknown Source)
    at baritone.j.onTick(Unknown Source)
    at baritone.cf.a(Unknown Source)
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:8[9](https://mclo.gs/srLHGOH#L9)5)
    at baritone.cf.onTick(Unknown Source)
    at net.minecraft.client.Minecraft.handler$zdo000$runTick(Minecraft.java)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1755)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:[10](https://mclo.gs/srLHGOH#L10)98)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4[11](https://mclo.gs/srLHGOH#L11)4)
    at net.minecraft.client.main.Main.main(SourceFile:[12](https://mclo.gs/srLHGOH#L12)3)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:[13](https://mclo.gs/srLHGOH#L13)5)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:[14](https://mclo.gs/srLHGOH#L14)4)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)`

**Comment by Rongmario** [comment]
I won't support hacking utilities, it is also not a fix I could do on my end.
