### ISSUE TITLE
datastructures.deobf.DeobfuscatedMappingsMap NullPointer

### ISSUE THREAD

**Issue by Rsslone** [LoliKingdom/LoliASM#157]
Noticed this NullPointerException right after coremod loading.

`[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: java.lang.NullPointerException
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.lang.String.startsWith(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.lang.String.startsWith(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.api.datastructures.deobf.DeobfuscatedMappingsMap.lambda$put$0(DeobfuscatedMappingsMap.java:40)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.HashMap$ValueSpliterator.tryAdvance(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.api.datastructures.deobf.DeobfuscatedMappingsMap.put(DeobfuscatedMappingsMap.java:40)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.api.datastructures.deobf.DeobfuscatedMappingsMap.put(DeobfuscatedMappingsMap.java:17)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at it.unimi.dsi.fastutil.objects.AbstractObject2ObjectMap.putAll(AbstractObject2ObjectMap.java:134)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.putAll(Object2ObjectOpenHashMap.java:299)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:187)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.<init>(Object2ObjectOpenHashMap.java:198)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.api.datastructures.deobf.DeobfuscatedMappingsMap.<init>(DeobfuscatedMappingsMap.java:30)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.api.datastructures.deobf.DeobfuscatedMappingsMap.of(DeobfuscatedMappingsMap.java:24)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.core.LoliFMLCallHook.call(LoliFMLCallHook.java:34)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at zone.rong.loliasm.core.LoliFMLCallHook.call(LoliFMLCallHook.java:20)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.inject(MixinPlatformAgentFMLLegacy.java:333)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at org.spongepowered.asm.launch.platform.MixinContainer.inject(MixinContainer.java:143)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:191)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:64)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[03:55:37] [main/INFO] [STDERR]: [zone.rong.loliasm.core.LoliFMLCallHook:call:44]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)`

**Comment by Rongmario** [comment]
This shouldn't crash the game right? I'll explicitly check for this in v6 though.

**Comment by Rsslone** [comment]
Right, doesn't crash. Just thought I'd report anyways.
