### ISSUE TITLE
Crash with OptiFine (originally Foamfix)

### ISSUE THREAD

**Issue by Romz24** [LoliKingdom/LoliASM#169]
When loading reaches the main menu, I encounter a crash related to FoamFix. This issue was not present in previous versions up to 5.9, and it started occurring after today's update.

Loliasm version: **5.9**
Foamfix version: **0.10.15**

```
java.lang.NullPointerException
    at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
    at net.minecraft.client.renderer.texture.TextureUtil.copyToBufferPos(TextureUtil.java:328)
    at net.minecraft.client.renderer.texture.TextureUtil.uploadTextureSub(TextureUtil.java:199)
    at pl.asie.foamfix.client.FastTextureAtlasSprite.uploadTextureMaxMips(FastTextureAtlasSprite.java:228)
    at pl.asie.foamfix.client.FastTextureAtlasSprite.updateAnimationInterpolated(FastTextureAtlasSprite.java:167)
    at pl.asie.foamfix.client.FastTextureAtlasSprite.updateAnimation(FastTextureAtlasSprite.java:116)
    at net.minecraft.client.renderer.texture.TextureMap.updateAnimations(TextureMap.java:577)
    at net.minecraft.client.renderer.texture.TextureMap.tick(TextureMap.java:711)
    at net.minecraft.client.renderer.texture.TextureManager.tick(TextureManager.java:167)
    at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:342)
    at net.optifine.util.TextureUtils$1.onResourceManagerReload(TextureUtils.java:362)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
    at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:366)
    at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2818)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1312)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Full crash log: https://mclo.gs/PWhfvLJ

**Comment by KorewaLidesu** [comment]
Send debug log up here

**Comment by Romz24** [comment]
> Upload debug log

- [debug.log](https://github.com/LoliKingdom/LoliASM/files/11555812/debug.log)
- [latest.log](https://github.com/LoliKingdom/LoliASM/files/11555820/latest.log)
- [crash-2023-05-24_17.32.50-client.txt](https://github.com/LoliKingdom/LoliASM/files/11555818/crash-2023-05-24_17.32.50-client.txt)

**Comment by Rongmario** [comment]
Can you try without OptiFine, just to check?

**Comment by Romz24** [comment]
> Can you try without OptiFine

The main menu does load properly. However, now when I try to enter a world, the game crashes, and this is also related to FoamFix.

Files:
- [crash-2023-05-25_00.21.29-client.txt](https://github.com/LoliKingdom/LoliASM/files/11559297/crash-2023-05-25_00.21.29-client.txt)
- [debug.log](https://github.com/LoliKingdom/LoliASM/files/11559298/debug.log)
- [latest.log](https://github.com/LoliKingdom/LoliASM/files/11559301/latest.log)

**Comment by Krutoy242** [comment]
This issue is still happen on my modpack `E2E-E` even on 5.12  
https://mclo.gs/e8HRY50

**Comment by Rongmario** [comment]
@Krutoy242 can you remove Foamfix and try?

**Comment by Krutoy242** [comment]
Removing Optifine fix the issue.
I can't reproduce the issue, but people say that restarting game couple of times fix the issue without changing anything.
