### ISSUE TITLE
Issue in censoredasm 5.9 on CAT server.

### ISSUE THREAD

**Issue by Artronah1** [LoliKingdom/LoliASM#171]
[12:37:42] [main/INFO] [LoliASM]: Improving FurnaceRecipes. Lookups are now a lot faster.
[12:37:42] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_CLASSLOADER_EXCLUSION] encountered loading mixins.fccb.json:bukkit.IMixinPluginClassLoader, name: fr.terrainwax.fccb.mixins.bukkit.IMixinPluginClassLoader
[12:37:42] [main/WARN] [mixin]: @Mixin target org.bukkit.plugin.java.PluginClassLoader is public in mixins.fccb.json:bukkit.IMixinPluginClassLoader and should be specified in value
[12:37:42] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_372]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [CatServer-fed56812-universal.jar:git-CatServer-1.12.2-fed56812]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [CatServer-fed56812-universal.jar:git-CatServer-1.12.2-fed56812]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at catserver.server.CatServerLaunch.main(CatServerLaunch.java:17) [CatServer-fed56812-universal.jar:git-CatServer-1.12.2-fed56812]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-7.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector setPriorityAndStart(Ljava/lang/Thread;)V in mixins.priorities.json:MinecraftServerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.loliasm.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[!mixinbooter-7.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-7.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 17 more

**Comment by Rongmario** [comment]
I can't do much as these server jars differ largely to Forge, same with LoliServer, Magma, Mohist and such.
