### ISSUE TITLE
Crashes with Baritone when entering world

### ISSUE THREAD

**Issue by NobodyHere-rrr** [LoliKingdom/LoliASM#177]
### **Version**
LoliASM: 5.12
Baritione: 1.2.17

### **Crash Report**
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// This doesn't make any sense!

Time: 2023-06-08 11:08:04 CST
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.BlockPos.field_177990_b from class baritone.api.utils.BetterBlockPos
    at baritone.api.utils.BetterBlockPos.<init>(Unknown Source)
    at baritone.api.utils.BetterBlockPos.<clinit>(Unknown Source)
    at baritone.api.utils.IPlayerContext.playerFeet(Unknown Source)
    at baritone.g.a(Unknown Source)
    at baritone.g.onTick(Unknown Source)
    at baritone.br.a(Unknown Source)
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
    at baritone.br.onTick(Unknown Source)
    at net.minecraft.client.Minecraft.handler$zzj000$runTick(Minecraft.java)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1755)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

(MixinBooter) Mixins in Stacktrace:
    net.minecraft.client.Minecraft:
        zone.rong.loliasm.client.searchtree.mixins.vanilla.MinecraftMixin (mixins.searchtree_vanilla.json)
        zone.rong.loliasm.common.crashes.mixins.MinecraftMixin (mixins.crashes.json)
        baritone.launch.mixins.MixinMinecraft (mixins.baritone.json)
        zone.rong.loliasm.client.mcfixes.mixins.mc186052.MinecraftMixin (mixins.fix_mc186052.json)
        me.jellysquid.mods.phosphor.mixins.lighting.client.MixinMinecraft (mixins.phosphor.json)

**Comment by Rongmario** [comment]
Fixed in dev
