### ISSUE TITLE
Can't load into any world

### ISSUE THREAD

**Issue by Airisii** [LoliKingdom/LoliASM#189]
No matter the world, new or old, It does the "not responding" and stays stuck on the esc menu screen. I've left it alone for hours and it stays not responding and the fps will also stay at 0 on the screen (I have a fps mod that shows me the fps even when not in game).  It seems the only version of the mod that will work for me is Loliasm-4.13. Note this is with all my mods and I have tested without all my mods and it seems to work as intended. I'm assuming there is a mod conflict of some sort but I do not know what mod would be causing an issue. 

Log:
[2023-07-17-6.log](https://github.com/LoliKingdom/LoliASM/files/12081105/2023-07-17-6.log)

**Comment by Rongmario** [comment]
Would turning off OptiFine's Custom Item Textures help it?

**Comment by LegendaryCrystalFox** [comment]
I'll give it a try

**Comment by LegendaryCrystalFox** [comment]
I was able to replicate the black screen with fewer mods and it talks about loliasm/censoredasm in the crash report.


[crash-2023-07-19_15.59.45-client.txt](https://github.com/LoliKingdom/LoliASM/files/12099751/crash-2023-07-19_15.59.45-client.txt)

**Comment by embeddedt** [comment]
In the VintageFix Discord channel we linked this to `crashReportImprovements` being enabled, and getting a thread dump showed the following recursive call to `onAddEntityCrashInfo`. Turning off that option apparently fixed the issue.

```
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.md134793$censoredasm5_14$lambda$onAddEntityCrashInfo$0$0(Entity.java:8890)
	at net.minecraft.entity.Entity$$Lambda$18999/1820484779.call(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.entity.Entity.handler$zma000$censoredasm5_14$onAddEntityCrashInfo(Entity.java:8890)
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2707)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1771)
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:3133)
	at mchorse.vanilla_pack.MetamorphSection.addMorph(MetamorphSection.java:115)
	at mchorse.vanilla_pack.MetamorphSection.update(MetamorphSection.java:62)
	at mchorse.metamorph.api.MorphManager.setActiveBlacklist(MorphManager.java:100)
	at mchorse.metamorph.network.client.ClientHandlerBlacklist.run(ClientHandlerBlacklist.java:16)
	at mchorse.metamorph.network.client.ClientHandlerBlacklist.run(ClientHandlerBlacklist.java:11)
	at mchorse.mclib.network.ClientMessageHandler$1.run(ClientMessageHandler.java:31)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:529)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5614)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Rongmario** [comment]
Fixed in v6, will look to push the fix to v5 too.
