### ISSUE TITLE
failure when opening the thermal expansion bag

### ISSUE THREAD

**Issue by FireV1ndicator** [LoliKingdom/LoliASM#193]
Censored asm version: 5.14
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Hey, that tickles! Hehehe!

Time: 2023-08-01 10:03:59 YEKT
Description: Ticking player

java.lang.NoClassDefFoundError: cofh/thermalexpansion/gui/container/storage/ContainerSatchel
    at cofh.thermalexpansion.proxy.EventHandler.handleEntityItemPickup(EventHandler.java:28)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2250_EventHandler_handleEntityItemPickup_EntityItemPickupEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:513)
    at net.minecraft.entity.item.EntityItem.onCollideWithPlayer(EntityItem.java:396)
    at net.minecraft.entity.player.EntityPlayer.collideWithPlayer(EntityPlayer.java:600)
    at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:571)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.gui.container.storage.ContainerSatchel
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 20 more
Caused by: java.lang.NoClassDefFoundError: cofh/core/gui/container/ContainerInventoryItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 22 more
Caused by: java.lang.ClassNotFoundException: cofh.core.gui.container.ContainerInventoryItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 26 more

**Comment by Rongmario** [comment]
This is an issue between MixinBooter 8, DupefixProject and Thermal. https://github.com/LoliKingdom/MixinBooter/issues/34
