### ISSUE TITLE
Issues with SpongeForge 

### ISSUE THREAD

**Issue by JustZerooo** [LoliKingdom/LoliASM#209]
Here are somthing from my logs 👍 
```
[20:56:10] [main/WARN]: @Redirect conflict. Skipping mixins.forge.optimization.json:threadchecks.MinecraftServerMixin_ForgeThreadChecks from mod unknown-owner->@Redirect::forgeThreadChecks$updateServerThread(Ljava/lang/Thread;)V with priority 1000, already redirected by mixins.priorities.json:MinecraftServerMixin from mod unknown-owner->@Redirect::setPriorityAndStart(Ljava/lang/Thread;)V with priority 1000
[20:56:10] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_371]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_371]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_371]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_371]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_371]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_371]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_371]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2860.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:406) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-8.6.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector forgeThreadChecks$updateServerThread(Ljava/lang/Thread;)V in mixins.forge.optimization.json:threadchecks.MinecraftServerMixin_ForgeThreadChecks from mod unknown-owner failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.forge.refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[!mixinbooter-8.6.jar:?]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[!mixinbooter-8.6.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 12 more
A problem occurred running the Server launcher.[20:56:10] [main/INFO]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
```

![https://i.imgur.com/6YNE7Yv.png](https://i.imgur.com/6YNE7Yv.png)

**Comment by Rongmario** [comment]
Fixed in dev with PR #199

**Comment by JustZerooo** [comment]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/12642518/latest.log)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/12642519/debug.log)
Not really as i tested with pure spongeforge loliasm and mixinbooster as required

**Comment by KorewaLidesu** [comment]
> [latest.log](https://github.com/LoliKingdom/LoliASM/files/12642518/latest.log) [debug.log](https://github.com/LoliKingdom/LoliASM/files/12642519/debug.log) Not really as i tested with pure spongeforge loliasm and mixinbooster as required

`in dev`

**Comment by JustZerooo** [comment]
i see no in dev branch

**Comment by KorewaLidesu** [comment]
> i see no in dev branch

dude, it is in the *dev* on Rong computer 🤣

**Comment by Rongmario** [comment]
Did you turn off the `threadPriorityFix` config option?

**Comment by JustZerooo** [comment]
i should do this?

**Comment by KorewaLidesu** [comment]
Yes

**Comment by JustZerooo** [comment]
A workaround : :)

**Comment by Levkovalev** [comment]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/12665799/latest.log)
Same issue, disabled threadsPriorityFix, but for some reason problem stays
[loliasm.txt](https://github.com/LoliKingdom/LoliASM/files/12665809/loliasm.txt)
(I changed from cfg to txt)
