### ISSUE TITLE
[1.12.2] possible bug with CreativeMD/LittleTiles doors

### ISSUE THREAD

**Issue by InuYasha86000** [LoliKingdom/LoliASM#217]
I am not sure if this is directly caused by LoliASM but I tried 3 different hybrid servers and they all come back with this error:

[15:47:32] [Server thread/INFO] [Mohist]: -------- World Settings For [world] --------
[15:47:32] [Server thread/INFO] [Mohist]: Experience Merge Radius: 3
[15:47:32] [Server thread/INFO] [Mohist]: Nerfing mobs spawned from spawners: false
[15:47:32] [Server thread/INFO] [Mohist]: Arrow Despawn Rate: 1200
[15:47:32] [Server thread/INFO] [Mohist]: Entity Tracking Range: players 48 / animals 48 / monsters 48 / misc 32 / other 64
[15:47:32] [Server thread/INFO] [Mohist]: Mob Spawn Range: 4
[15:47:32] [Server thread/INFO] [Mohist]: Max TNT Explosions: 100
[15:47:32] [Server thread/INFO] [Mohist]: Cactus Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Cane Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Melon Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Mushroom Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Pumpkin Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Sapling Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Wheat Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: NetherWart Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Vine Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Cocoa Growth Modifier: 100%
[15:47:32] [Server thread/INFO] [Mohist]: Tile Max Tick Time: 50 ms Entity max Tick Time: 50 ms
[15:47:32] [Server thread/INFO] [Mohist]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:47:32] [Server thread/INFO] [Mohist]: Random Lighting Updates: false
[15:47:32] [Server thread/INFO] [Mohist]: Structure Info Saving: true
[15:47:32] [Server thread/INFO] [Mohist]: Entity Activation Range: animals 32 / monsters 32 / misc 16 / tick-inactive-villagers true
[15:47:32] [Server thread/INFO] [Mohist]: Zombie Aggressive Towards Villager: true
[15:47:32] [Server thread/INFO] [Mohist]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:47:32] [Server thread/INFO] [Mohist]: View Distance: 10
[15:47:32] [Server thread/INFO] [Mohist]: Item Despawn Rate: 6,000
[15:47:32] [Server thread/INFO] [Mohist]: Item Merge Radius: 2.5
[15:47:32] [Server thread/INFO] [Mohist]: Max height for cactus growth 3. Max height for reed growth 3
[15:47:32] [Server thread/INFO] [Mohist]: Custom Map Seeds: Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[15:47:32] [Server thread/DEBUG] [LoliASM]: net.minecraft.util.Util = h = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/h.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: net.minecraft.server.MinecraftServer = net.minecraft.server.MinecraftServer = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/net/minecraft/server/MinecraftServer.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: net.minecraft.server.dedicated.DedicatedServer = nz = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/nz.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: net.minecraft.world.World = amu = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/amu.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles = com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/LittleTiles_v1.5.82_mc1.12.2.jar!/com/creativemd/littletiles/common/tileentity/TileEntityLittleTiles.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.littletiles.common.world.LittleNeighborUpdateCollector = com.creativemd.littletiles.common.world.LittleNeighborUpdateCollector = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/LittleTiles_v1.5.82_mc1.12.2.jar!/com/creativemd/littletiles/common/world/LittleNeighborUpdateCollector.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.creativecore.common.world.NeighborUpdateCollector = com.creativemd.creativecore.common.world.NeighborUpdateCollector = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/CreativeCore_v1.10.71_mc1.12.2.jar!/com/creativemd/creativecore/common/world/NeighborUpdateCollector.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.littletiles.common.util.place.Placement = com.creativemd.littletiles.common.util.place.Placement = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/LittleTiles_v1.5.82_mc1.12.2.jar!/com/creativemd/littletiles/common/util/place/Placement.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.littletiles.common.structure.type.door.LittleDoorBase = com.creativemd.littletiles.common.structure.type.door.LittleDoorBase = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/LittleTiles_v1.5.82_mc1.12.2.jar!/com/creativemd/littletiles/common/structure/type/door/LittleDoorBase.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.littletiles.common.structure.type.door.LittleDoor = com.creativemd.littletiles.common.structure.type.door.LittleDoor = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/LittleTiles_v1.5.82_mc1.12.2.jar!/com/creativemd/littletiles/common/structure/type/door/LittleDoor.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.littletiles.common.packet.LittleActivateDoorPacket = com.creativemd.littletiles.common.packet.LittleActivateDoorPacket = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/LittleTiles_v1.5.82_mc1.12.2.jar!/com/creativemd/littletiles/common/packet/LittleActivateDoorPacket.class
[15:47:32] [Server thread/DEBUG] [LoliASM]: com.creativemd.creativecore.common.packet.PacketReciever$2 = com.creativemd.creativecore.common.packet.PacketReciever$2 = jar:file:/D:/.Minecraft%20Servers/minecraft%20modpack%201.12.2/./mods/CreativeCore_v1.10.71_mc1.12.2.jar!/com/creativemd/creativecore/common/packet/PacketReciever$2.class
[15:47:32] [Server thread/FATAL] [LoliASM]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_381]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_381]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.handler$zcp000$checkLightFor(World.java:4571) ~[amu.class:?]
	at net.minecraft.world.World.checkLightFor(World.java) ~[amu.class:?]
	at net.minecraft.world.World.checkLight(World.java:3202) ~[amu.class:?]
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateLighting(TileEntityLittleTiles.java:177) ~[TileEntityLittleTiles.class:?]
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:260) ~[TileEntityLittleTiles.class:?]
	at com.creativemd.littletiles.common.world.LittleNeighborUpdateCollector.processPosition(LittleNeighborUpdateCollector.java:45) ~[LittleNeighborUpdateCollector.class:?]
	at com.creativemd.creativecore.common.world.NeighborUpdateCollector.process(NeighborUpdateCollector.java:54) ~[NeighborUpdateCollector.class:?]
	at com.creativemd.littletiles.common.util.place.Placement.placeTiles(Placement.java:247) ~[Placement.class:?]
	at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:198) ~[Placement.class:?]
	at com.creativemd.littletiles.common.util.place.Placement.tryPlace(Placement.java:209) ~[Placement.class:?]
	at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.place(LittleDoorBase.java:209) ~[LittleDoorBase.class:?]
	at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.openDoor(LittleDoorBase.java:270) ~[LittleDoorBase.class:?]
	at com.creativemd.littletiles.common.structure.type.door.LittleDoor.activate(LittleDoor.java:103) ~[LittleDoor.class:?]
	at com.creativemd.littletiles.common.packet.LittleActivateDoorPacket.executeServer(LittleActivateDoorPacket.java:65) ~[LittleActivateDoorPacket.class:?]
	at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_381]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
[15:47:47] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world

LittleTiles makes small dimentions for there doors to store the blocks in during block state changes.

**Comment by KorewaLidesu** [comment]
Have you try with... vanilla server instead?

**Comment by InuYasha86000** [comment]
it turns out it's a combination of things. magma changed something in there code 3 months ago and I have found the version that works with no other mods installed, but I now have to track down which mod could be causing the door issue now.

**Comment by Rongmario** [comment]
Any updates?

**Comment by InuYasha86000** [comment]
this turns out to be an issue with hybrid servers (magma, mhoist, cat) it's with how they handle small dimentions or "worlds" that hold the blocks for the doors. here's the gitlab issue topic:

https://git.magmafoundation.org/magmafoundation/Magma/-/issues/597

**Comment by Rongmario** [comment]
Ah, this is similar to the GregTech - Valkyrie Skies issue then. I'll close this.
