### ISSUE TITLE
Serverside crash

### ISSUE THREAD

**Issue by ChromaPIE** [LoliKingdom/LoliASM#225]
Using censoredasm5.18

```
Caused by: java.lang.RuntimeException: Attempted to load class zone/rong/loliasm/client/LoliIncompatibilityHandler$Exception for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 41 more
```

**Comment by Rongmario** [comment]
Yeah, the server triggers a GUI class that doesn't exist, it'll be fixed soon:tm:

**Comment by Rongmario** [comment]
Duplicate of #147
