### ISSUE TITLE
Load crash: `ClassFormatError: Duplicate field name "rtFullBright" in class VertexLighterFlat`

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/LoliASM#251]
Sometimes about 1 per 50 launching E2EE, game wont start. During load its crashing with this error:

```ruby
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/pipeline/VertexLighterFlat
at net.minecraft.client.renderer.BlockRendererDispatcher.<init>(BlockRendererDispatcher.java:31)
at net.minecraft.client.Minecraft.init(Minecraft.java:525)
at net.minecraft.client.Minecraft.run(Minecraft.java:7101)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.pipeline.VertexLighterFlat
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 10 more

Caused by: java.lang.ClassFormatError: Duplicate field name "rtFullBright" with signature "Z" in class file net/minecraftforge/client/model/pipeline/VertexLighterFlat
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.security.SecureClassLoader.defineClass(Unknown Source)
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
... 12 more
```

https://mclo.gs/TH8yjpr

We searched for the reason of this crash many months already, and just recently, with `-Dmixin.debug.export=true` java args, i found that this class is modified with LoliASM.

- This crash is ignoreable for most players, since its can be fixed by just restarting client several times.
- For other, they cant get rid of it in 6+ restart amounts. So the issue is annoying and doesnt let some players enjoy E2EE.
- Want to mention that Optifine is not present in the logs above, thus its not a OF compat issue
- Also, we tried to remove mods to test if they are the problem, but they are not: `HammerCore`, `SledgeHammer`, `UniversalTweaks`.

**Comment by Krutoy242** [comment]
Further investigation shows that removing LoliASM wont have effect.
[crash-2024-06-14_14.25.40-client.txt](https://github.com/user-attachments/files/15838758/crash-2024-06-14_14.25.40-client.txt)

Its strange, because in `.mixin.out` i found only LoliaASM that making mixins: 
[VertexLighterFlat.java](https://github.com/user-attachments/files/15838774/VertexLighterFlat.java.txt)

**Comment by Krutoy242** [comment]
Im closing the issue, since its not LoliASM probably, but verbal help how I could find reason of this error is appreciated 😅
