### ISSUE TITLE
Crash: NPE on opening JEI - Industrial Wires compat

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/LoliASM#53]
After installed LoliASM, i opened JEI, and when started to write "Controller" in search bar, game crash occured:
```java
java.lang.NullPointerException
    at malte0811.industrialwires.client.ClientProxy.isValidTextureSource(ClientProxy.java:480)
    at malte0811.industrialwires.controlpanel.PanelUtils.generateQuads(PanelUtils.java:72)
    at malte0811.industrialwires.client.panelmodel.PanelModel$AssembledBakedModel.getQuads(PanelModel.java:127)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:168)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:136)
    at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
    at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
    at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:163)
    at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
    at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
    at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
    at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4793_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
[debug-1.log.gz](https://github.com/LoliKingdom/LoliASM/files/7553959/debug-1.log.gz)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
```

Full log:
[debug.log](https://github.com/LoliKingdom/LoliASM/files/7553959/debug-1.log.gz)

**Comment by Rongmario** [comment]
Think it may be a duplicate with: https://github.com/LoliKingdom/LoliASM/issues/32.

I haven't had time to check what IndustrialWires is specifically doing that is incompatible.

**Comment by Rongmario** [comment]
This should be fixed with https://github.com/LoliKingdom/LoliASM/commit/ea566aa9df65060ddb20b96b7717166f75277c09.
