### ISSUE TITLE
Corail Tombstone Crashes on First World Load

### ISSUE THREAD

**Issue by Handeril** [LoliKingdom/LoliASM#73]
First of all, I'd like to say - I'm amazed with the performance difference I've seen with this mod installed, and being able to scroll through all of the items in the game without causing the game to start lagging is a HUGE plus. Unexpectedly, it may have also fixed some texture errors I was having between two mods, which surprised me, but I'm not "jumping the gun" on that one (still testing).

With that shared, I'll get into the "meat and potatoes" of the issue. Every time the game is booted, or rebooted, Corail Tombstone will vomit up this error when you try to load a world for the first time:

If you need other files, I will be happy to provide them, just let me know where to find them or how to get them.

---- Minecraft Crash Report ----
// My bad.

Time: 2022-04-23 14:34:53 PDT
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Corail Tombstone (tombstone)
Caused by: java.lang.InstantiationError: com.favouritedragon.arcaneessentials.common.entity.EntityMagicSpawner
    at zone.rong.loliasm.LoliReflector$$Lambda$1914/2033262966.apply(Unknown Source)
    at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68)
    at ovh.corail.tombstone.helper.TameableType.init(TameableType.java:54)
    at ovh.corail.tombstone.ModTombstone.onServerStarted(ModTombstone.java:129)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:797)
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:158)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Rongmario** [comment]
First of all, thank you for the kind message and I'm glad this mod has helped you in some way.

As for the bug, you can switch off `fasterEntitySpawnPreparation` until the next update.

**Comment by Rongmario** [comment]
By the way, it'd be great if you can provide a log file.

**Comment by Handeril** [comment]
Just let me which to grab, and where it is.

**Comment by Rongmario** [comment]
Should be `.minecraft/logs/latest.log` providing you crashed in the latest load.

**Comment by Handeril** [comment]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8548693/latest.log)

**Comment by Handeril** [comment]
There's also a spamming error, as there is a running world atm

**Comment by Rongmario** [comment]
Thanks, thats good enough, no need for the apology.

I also noticed some stuff in your log and thought I'd point them out, just some of my advice that's all:

1. `TC6 Aspects 4 JEI` isn't really needed when you have `ThaumicJEI`, they have duplicate functionality and `ThaumicJEI` is more performant.
2. Try out something that I'm developing under [`CleanroomMC`](https://cleanroommc.com/), [`HadEnoughItems`](https://www.curseforge.com/minecraft/mc-mods/had-enough-items): its a JEI fork that aims to optimize it and bring forth new features.
3. Another mod of mine, this one combats Thaumcraft's loading speed: [`Thaumic Speedup`](https://www.curseforge.com/minecraft/mc-mods/thaumic-speedup)

**Comment by Handeril** [comment]
I'll see about adding HadEnoughItems when the project is official [so that it's not a huge hassle for my friends, who have been testing the modpack, to update].

Removed TC6 Aspects 4 JEI, since it's _just_ deleting a file.

I'll see about adding Thaumic Speedup right now.

**Comment by Handeril** [comment]
If you have any more advice, I'm sure we can chat more via Discord or otherwise.

I've switched off fasterEntitySpawnPreparation for now, like you suggested - though, I have confidence that an update that'll possibly fix this issue might be out before the modpack update goes out for testing.

**Comment by Rongmario** [comment]
Np, my discord tag atm is `Rongmario#9898`

**Comment by Rongmario** [comment]
Just had a good look at this error again, can you try installing this Arcane Essentials version (latest, beta) instead?: https://www.curseforge.com/minecraft/mc-mods/arcane-essentials/files/3205508

**Comment by Handeril** [comment]
Trying the solution now - I think I was using an older version because of the newer version causing a crash on world load, or a crash on casting spells... I forget which, honestly.

**Comment by Handeril** [comment]
It didn't work, and Git isn't allowing me to post the log.
