### ISSUE TITLE
Incompatible screen does not pop-up in time when installed with VanillaFix

### ISSUE THREAD

**Issue by ChAoSUnItY** [LoliKingdom/LoliASM#88]
LoliASM 5.0 crashes on TNFC latest version (12.2.80).

At first glance this seems like ASM class transformation's issue

Edit 1: After removed vanillafix, the conflicting issue resolved, maybe this mod confliction is not considered as expected behavior?

```
---- Minecraft Crash Report ----
// My bad.

Time: 2022-05-06 11:08:29 CST
Description: Initializing game

java.lang.IncompatibleClassChangeError: Conflicting default methods: org/dimdev/vanillafix/crashes/StateManager$IResettable.register zone/rong/loliasm/common/crashes/IStateful.register
    at net.minecraft.client.renderer.BufferBuilder.register(BufferBuilder.java)
    at net.minecraft.client.renderer.BufferBuilder.handler$zcf000$onInit(BufferBuilder.java:700)
    at net.minecraft.client.renderer.BufferBuilder.<init>(BufferBuilder.java:45)
    at net.minecraft.client.renderer.Tessellator.<init>(SourceFile:17)
    at net.minecraft.client.renderer.Tessellator.<clinit>(SourceFile:10)
    at net.minecraft.client.renderer.texture.TextureMap.handler$zek000$afterInit(TextureMap.java:1044)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:64)
    at mezz.jei.gui.textures.JeiTextureMap.<init>(JeiTextureMap.java:33)
    at mezz.jei.startup.ProxyCommonClient.<init>(ProxyCommonClient.java:51)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 417699576 bytes (398 MB) / 1073741824 bytes (1024 MB) up to 8489271296 bytes (8096 MB)
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8096m -Xms256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.0 Powered by Forge 14.23.5.2860 143 mods loaded, 142 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                          | Version                      | Source                                                         | Signature                                |
       |:----- |:--------------------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
       | LC    | minecraft                   | 1.12.2                       | minecraft.jar                                                  | None                                     |
       | LC    | mcp                         | 9.42                         | minecraft.jar                                                  | None                                     |
       | LC    | FML                         | 8.0.99.99                    | forge-1.12.2-14.23.5.2860.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | forge                       | 14.23.5.2860                 | forge-1.12.2-14.23.5.2860.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | creativecoredummy           | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | LC    | littletilescore             | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | LC    | mixinbooter                 | 4.2                          | minecraft.jar                                                  | None                                     |
       | LC    | openmodscore                | 0.12.2                       | minecraft.jar                                                  | None                                     |
       | LC    | biometweakercore            | 1.0.39                       | minecraft.jar                                                  | None                                     |
       | LC    | bnbgamingcore               | 0.12.0                       | minecraft.jar                                                  | None                                     |
       | LC    | opencomputers|core          | 1.7.5.192                    | minecraft.jar                                                  | None                                     |
       | LC    | randompatches               | 1.12.2-1.22.1.10             | randompatches-1.12.2-1.22.1.10.jar                             | None                                     |
       | LC    | crafttweaker                | 4.1.20                       | CraftTweaker2-1.12-4.1.20.674.jar                              | None                                     |
       | LC    | mtlib                       | 3.0.7                        | MTLib-3.0.7.jar                                                | None                                     |
       | LC    | modtweaker                  | 4.0.19                       | modtweaker-4.0.20.5.jar                                        | None                                     |
       | L     | jei                         | 4.16.1.302                   | jei_1.12.2-4.16.1.302.jar                                      | None                                     |
       | L     | loliasm                     | 5.0                          | loliasm-5.0.jar                                                | None                                     |
       | L     | forgeendertech              | 1.12.2-4.5.6.0               | ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar                   | None                                     |
       | L     | adhooks                     | 1.12.2-3.3.1.0               | AdHooks-1.12.2-3.3.1.0-build.0626.jar                          | None                                     |
       | L     | redstoneflux                | 2.1.1                        | RedstoneFlux-1.12-2.1.1.1-universal.jar                        | None                                     |
       | L     | cofhcore                    | 4.6.6                        | CoFHCore-1.12.2-4.6.6.1-universal.jar                          | None                                     |
       | L     | engineersdecor              | 1.1.4                        | engineersdecor-1.12.2-1.1.4.jar                                | None                                     |
       | L     | immersiveengineering        | 0.12-98                      | ImmersiveEngineering-0.12-98.jar                               | None                                     |
       | L     | libvulpes                   | 0.4.2.-88                    | LibVulpes-1.12.2-0.4.2-88-universal.jar                        | None                                     |
       | L     | advancedrocketry            | 2.0.0.-257                   | AdvancedRocketry-1.12.2-2.0.0-257-universal.jar                | None                                     |
       | L     | immersivepetroleum          | 1.1.10                       | immersivepetroleum-1.12.2-1.1.10.jar                           | None                                     |
       | L     | waila                       | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                                    | None                                     |
       | L     | tfc                         | 1.7.23.181                   | TerraFirmaCraft-MC1.12.2-1.7.23.181.jar                        | None                                     |
       | L     | att                         | 0.2.3                        | AdvancedTFCTech-0.2.3.jar                                      | None                                     |
       | L     | animalnet                   | v1.12.2 b3                   | animalnet-v1.12.2 b3.jar                                       | None                                     |
       | L     | astikorcarts                | 1.12.2-0.1.2.8               | astikorcarts-1.12.2-0.1.2.8.jar                                | None                                     |
       | L     | athenaeum                   | 1.12.2-1.19.5                | athenaeum-1.12.2-1.19.5.jar                                    | None                                     |
       | L     | ctm                         | MC1.12.2-1.0.2.31            | CTM-MC1.12.2-1.0.2.31.jar                                      | None                                     |
       | L     | betterwithmods              | 1.12-2.3.24                  | BetterWithMods-1.12-2.3.24.jar                                 | None                                     |
       | L     | jaff                        | 1.7_for_1.12                 | JustAFewFish-1.7_for_1.12.jar                                  | None                                     |
       | L     | mcwbridges                  | 1.0.6                        | mcw-bridges-1.0.6b-mc1.12.2.jar                                | None                                     |
       | L     | mineraltracker              | ${version}                   | MineralTracker-0.9.3.jar                                       | None                                     |
       | L     | bookshelf                   | 2.3.590                      | Bookshelf-1.12.2-2.3.590.jar                                   | None                                     |
       | L     | gbook                       | 2.9.5                        | Guidebook-1.12.2-2.9.5.jar                                     | None                                     |
       | L     | rockhounding_core           | 3.27                         | rockhounding_core-1.12.2-3.27.jar                              | None                                     |
       | L     | rockhounding_chemistry      | 1.12.2-3.62                  | rockhounding_chemistry-1.12.2-3.62.jar                         | None                                     |
       | L     | firstaid                    | 1.6.13                       | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | tnfcmod                     | 12.2.80                      | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | autoreglib                  | 1.3-32                       | AutoRegLib-1.3-32.jar                                          | None                                     |
       | L     | autowalk                    | 1.1                          | autowalk-1.12.2-1.0.jar                                        | None                                     |
       | L     | baubles                     | 1.5.2                        | Baubles-1.12-1.5.2.jar                                         | None                                     |
       | L     | betterwithengineering       | 1.2                          | BetterWithEngineering-1.6.jar                                  | None                                     |
       | L     | betterwithlib               | ${version}                   | BetterWithLib-1.12-1.5.jar                                     | None                                     |
       | L     | biometweaker                | 3.2.369                      | BiomeTweaker-1.12.2-3.2.369.jar                                | None                                     |
       | L     | bnbgaminglib                | 2.17.6                       | BNBGamingLib-1.12.2-2.17.6.jar                                 | None                                     |
       | L     | chameleon                   | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                                       | None                                     |
       | L     | chiselsandbits              | 14.33                        | chiselsandbits-14.33.jar                                       | None                                     |
       | L     | clienttweaks                | 3.1.11                       | ClientTweaks_1.12.2-3.1.11.jar                                 | None                                     |
       | L     | controlling                 | 3.0.10                       | Controlling-3.0.10.jar                                         | None                                     |
       | L     | craftingtweaks              | 8.1.9                        | CraftingTweaks_1.12.2-8.1.9.jar                                | None                                     |
       | L     | ctgui                       | 1.0.0                        | CraftTweaker2-1.12-4.1.20.674.jar                              | None                                     |
       | L     | crafttweakerjei             | 2.0.3                        | CraftTweaker2-1.12-4.1.20.674.jar                              | None                                     |
       | L     | creativecore                | 1.10.0                       | CreativeCore_v1.10.70_mc1.12.2.jar                             | None                                     |
       | L     | customloadingscreen         | 1.12.2-1.5.5                 | CustomLoadingScreen-1.12.2-1.5.5.jar                           | None                                     |
       | L     | custommainmenu              | 2.0.9.1                      | CustomMainMenu-MC1.12.2-2.0.9.1.jar                            | None                                     |
       | L     | customnpcs                  | 1.12                         | CustomNPCs_1.12.2-(05Jul20).jar                                | None                                     |
       | L     | customstartinggear          | 1.2.0                        | CustomStartingGear-1.12-1.2.0.9-universal.jar                  | None                                     |
       | L     | debark                      | 0.1.2                        | Debark-0.1.2.jar                                               | None                                     |
       | L     | journeymap                  | 1.12.2-5.7.1                 | journeymap-1.12.2-5.7.1.jar                                    | None                                     |
       | L     | defaultoptions              | 9.2.8                        | DefaultOptions_1.12.2-9.2.8.jar                                | None                                     |
       | L     | dropt                       | 1.12.2-1.19.2                | dropt-1.12.2-1.19.2.jar                                        | None                                     |
       | L     | dynamiclights               | 1.4.9                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_onfire        | 1.0.7                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_creepers      | 1.0.6                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_dropitems     | 1.1.0                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_entityclasses | 1.0.1                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_mobequipment  | 1.1.0                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_flamearrows   | 1.0.1                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_floodlights   | 1.0.3                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_otherplayers  | 1.0.9                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | dynamiclights_theplayer     | 1.1.3                        | DynamicLights-1.12.2.jar                                       | None                                     |
       | L     | emojicord                   | 1.1.1.39                     | Emojicord-1.12.2-1.1.1.39-universal.jar                        | None                                     |
       | L     | reborncore                  | 3.19.5                       | RebornCore-1.12.2-3.19.5-universal.jar                         | None                                     |
       | L     | engineersworkshop           | 1.0.9.40                     | EngineersWorkshopReborn-1.12.2-1.0.9.40.jar                    | None                                     |
       | L     | fasterladderclimbing        | 0.1-146                      | FasterLadderClimbing-1.12-0.1-146.jar                          | None                                     |
       | L     | fastbench                   | 1.7.3                        | FastWorkbench-1.12.2-1.7.3.jar                                 | None                                     |
       | L     | firmalife                   | 0.5.1                        | firmalife-0.5.1.jar                                            | None                                     |
       | L     | forgelin                    | 1.8.4                        | Forgelin-1.8.4.jar                                             | None                                     |
       | L     | ftbbackups                  | 1.1.0.1                      | FTBBackups-1.1.0.1.jar                                         | None                                     |
       | L     | ftblib                      | 5.4.7.2                      | FTBLib-5.4.7.2.jar                                             | None                                     |
       | L     | ftbutilities                | 5.4.1.131                    | FTBUtilities-5.4.1.131.jar                                     | None                                     |
       | L     | immersivecables             | 1.3.2                        | ImmersiveCables-1.12.2-1.3.2.jar                               | None                                     |
       | L     | immersiveposts              | 0.2.1                        | ImmersivePosts-0.2.1.jar                                       | None                                     |
       | L     | inventorytweaks             | 1.63+release.109.220f184     | InventoryTweaks-1.63.jar                                       | None                                     |
       | L     | jeid                        | 1.0.3-55                     | JustEnoughIDs-1.0.3-55.jar                                     | None                                     |
       | L     | justenoughpetroleum         | 0.1                          | JustEnoughPetroleum-0.1.jar                                    | None                                     |
       | L     | jeresources                 | 0.9.2.60                     | JustEnoughResources-1.12.2-0.9.2.60.jar                        | None                                     |
       | L     | littletiles                 | 1.5.0                        | LittleTiles_v1.5.57_mc1.12.2.jar                               | None                                     |
       | L     | lostcities_tfc              | 12.2.66.1                    | lostcities_tfc-1.12-12.2.66.1.jar                              | None                                     |
       | L     | mcjtylib_ng                 | 3.5.4                        | mcjtylib-1.12-3.5.4.jar                                        | None                                     |
       | L     | immersivetech               | 1.8.94                       | MCTImmersiveTechnology-1.12.2-1.8.94.jar                       | None                                     |
       | L     | mcwdoors                    | 1.3                          | mcw-doors-1.0.3-mc1.12.2.jar                                   | None                                     |
       | L     | mcwfurnitures               | 1.0.1                        | mcw-furniture-1.0.1-mc1.12.2beta.jar                           | None                                     |
       | L     | mcwroofs                    | 1.0.2                        | mcw-roofs-1.0.2-mc1.12.2.jar                                   | None                                     |
       | L     | mcwwindows                  | 1.0                          | mcw-windows-1.0.0-mc1.12.2.jar                                 | None                                     |
       | L     | moarboats                   | 4.1.2.1                      | moarboats-1.12.2-4.1.2.1.jar                                   | None                                     |
       | L     | modernlamps                 | 1.0.3                        | ModernLights-1.0.3_1.12.jar                                    | None                                     |
       | L     | mousetweaks                 | 2.10.1                       | MouseTweaks-2.10.1-mc1.12.2.jar                                | None                                     |
       | L     | nuclearcraft                | 2o.5.5                       | NuclearCraft-2o.5.5-1.12.2.jar                                 | None                                     |
       | L     | openmods                    | 0.12.2                       | OpenModsLib-1.12.2-0.12.2.jar                                  | None                                     |
       | L     | openblocks                  | 1.8.1                        | OpenBlocks-1.12.2-1.8.1.jar                                    | None                                     |
       | L     | opencomputers               | 1.7.5.192                    | OpenComputers-MC1.12.2-1.7.5.192.jar                           | None                                     |
       | L     | oreveins                    | 2.0.15                       | oreveins-2.0.15.jar                                            | None                                     |
       | L     | parry                       | 1.0                          | parry-1.0-hotfix.jar                                           | None                                     |
       | L     | patchouli                   | 1.0-23.6                     | Patchouli-1.0-23.6.jar                                         | None                                     |
       | L     | placebo                     | 1.6.0                        | Placebo-1.12.2-1.6.0.jar                                       | None                                     |
       | L     | pneumaticcraft              | 1.12.2-0.11.15-398           | pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar            | None                                     |
       | L     | resourceloader              | 1.5.3                        | ResourceLoader-MC1.12.1-1.5.3.jar                              | None                                     |
       | L     | simplyjetpacks              | 1.12.2-2.2.20.0              | SimplyJetpacks2-1.12.2-2.2.20.0.jar                            | None                                     |
       | L     | simplyloaders               | 1.0.0                        | Simplyloaders-2.0.jar                                          | None                                     |
       | L     | sledgehammer                | 1.12.2-2.0.16                | Sledgehammer-1.12.2-2.0.16.jar                                 | None                                     |
       | L     | stg                         | 1.12.2-1.2.3                 | stg-1.12.2-1.2.3.jar                                           | None                                     |
       | L     | storagedrawers              | 5.2.2                        | StorageDrawers-1.12.2-5.4.2.jar                                | None                                     |
       | L     | sasit                       | 1.1.32                       | StuffASockInIt-1.12.2-1.1.32.jar                               | None                                     |
       | L     | surge                       | 2.0.79                       | Surge-1.12.2-2.0.79.jar                                        | None                                     |
       | L     | tfcthings                   | 1.3.5                        | terrafirmathings-1.3.5.jar                                     | None                                     |
       | L     | tfc_decoration              | 1.0.9                        | tfc_decoration-1.0.9.jar                                       | None                                     |
       | L     | tfcstorage                  | 1.0                          | TFCStorage-1.0.7.jar                                           | None                                     |
       | L     | tfctech                     | 1.2.16                       | TFCTech-Unofficial-MC1.12.2-1.2.16.jar                         | None                                     |
       | L     | time4tfc                    | 1.0.3                        | Time4TFC-MC1.12.2-1.0.3.jar                                    | None                                     |
       | L     | tips                        | 1.0.9                        | Tips-1.12.2-1.0.9.jar                                          | None                                     |
       | L     | aged_drinks                 | 12.2.65                      | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | storagedrawerstfc           | 12.2.48                      | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | tfcambiental                | 1.0                          | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | signpost                    | 1.08.5                       | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | horsepower                  | tnfc_12.2.13                 | TNFCMod-MC1.12.2-12.2.80.jar                                   | None                                     |
       | L     | toastcontrol                | 1.8.1                        | Toast Control-1.12.2-1.8.1.jar                                 | None                                     |
       | L     | triumph                     | 3.19.2                       | Triumph-1.12.2-3.19.2.jar                                      | None                                     |
       | L     | vanillafix                  | 1.0.10-150                   | VanillaFix-1.0.10-150.jar                                      | None                                     |
       | L     | waterflasks                 | 1.9                          | waterflasks-1.9.jar                                            | None                                     |
       | L     | wearablebackpacks           | 3.1.4                        | WearableBackpacks-1.12.2-3.1.4.jar                             | None                                     |
       | L     | weirdinggadget              | 1.0                          | weirdinggadget-1.12.2-2.1.16-universal.jar                     | None                                     |
       | L     | worldedit                   | 6.1.10                       | worldedit-forge-mc1.12.2-6.1.10-dist.jar                       | None                                     |
       | L     | worldeditcuife2             | 2.2.0-mf-1.12.2-14.23.5.2768 | WorldEdit CUI Forge Edition 2-2.2.0-mf-1.12.2-14.23.5.2768.jar | None                                     |
       | L     | worldutils                  | 0.4.2                        | worldutils-1.12.2-0.4.2.jar                                    | None                                     |
       | L     | xnet                        | 1.8.2                        | xnet-1.12-1.8.2.jar                                            | None                                     |
       | L     | ynot                        | 0.2.4                        | YNot-0.2.4.jar                                                 | None                                     |
       | UD    | advancedrocketrycore        | 1                            | minecraft.jar                                                  | None                                     |
  Loaded coremods (and transformers): EmojicordCorePlugin (Emojicord-1.12.2-1.1.1.39-universal.jar)
                                        net.teamfruit.emojicord.asm.EmojicordTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      LoliASM (loliasm-5.0.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
                                        me.superckl.biometweakercore.BiomeTweakerASMTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
                                      MixinBooter (!mixinbooter-4.2.jar)
                                        
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.12.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.5.5.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-257-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      DLFMLCorePlugin (DynamicLights-1.12.2.jar)
                                        atomicstryker.dynamiclights.common.DLTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.57_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001' Renderer: 'AMD Radeon RX 6600 XT'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
  Suspected Mods: Just Enough Items (jei)
  Suspected Mods: Just Enough Items (jei), Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: AMD Radeon RX 6600 XT GL version 4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: TFC Classic Music Pack.zip, TFC-TNG Soft Paths.zip, ctp_1.2_MCv3.zip, tfc-tng-faithful32-1.4.0.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700
```

**Comment by ModernGamingWorld** [comment]
@ChAoSUnItY The latest Beta does show a Huge update, now incompatible with TexFix and VanillaFix as this mod encapsulates and improves upon those mods.

**Comment by ChAoSUnItY** [comment]
I see, but after a review on latest commit, LoliASM should create a crash screen instead of crashing whole game with crashreport only.

Source: [LoliIncompatibilityHandler.java](https://github.com/LoliKingdom/LoliASM/blob/4.x/src/main/java/zone/rong/loliasm/client/LoliIncompatibilityHandler.java)

**Comment by Rongmario** [comment]
Send the whole log file over, wonder why it didn't show the crash screen?

**Comment by ChAoSUnItY** [comment]
[2022-05-06-3.log](https://github.com/LoliKingdom/LoliASM/files/8639874/2022-05-06-3.log)

**Comment by Rongmario** [comment]
Fixed in v6 branch, will be primed for its release.
